#! /bin/bash

grep -a "Sch_Exec_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/Sch_Exec.txt
awk '{print $7}' "Sch_Exec.txt" | xargs | tr " " "," > Sch_Exec.csv

grep -a "Sch_Jitter_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/Sch_Jitter.txt
awk '{print $7}' "Sch_Jitter.txt" | xargs | tr " " "," > Sch_Jitter.csv

grep -a "Mon_Exec_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/Mon_Exec.txt
awk '{print $7}' "Mon_Exec.txt" | xargs | tr " " "," > Mon_Exec.csv

grep -a "Mon_Jitter_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/Mon_Jitter.txt
awk '{print $7}' "Mon_Jitter.txt" | xargs | tr " " "," > Mon_Jitter.csv

grep -a "RGB_Exec_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/RGB_Exec.txt
awk '{print $7}' "RGB_Exec.txt" | xargs | tr " " "," > RGB_Exec.csv

grep -a "RGB_Jitter_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/RGB_Jitter.txt
awk '{print $7}' "RGB_Jitter.txt" | xargs | tr " " "," > RGB_Jitter.csv

grep -a "Store_Exec_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/Store_Exec.txt
awk '{print $7}' "Store_Exec.txt" | xargs | tr " " "," > Store_Exec.csv

grep -a "Store_Jitter_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/Store_Jitter.txt
awk '{print $7}' "Store_Jitter.txt" | xargs | tr " " "," > Store_Jitter.csv

grep -a "Sock_Exec_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/Sock_Exec.txt
awk '{print $7}' "Sock_Exec.txt" | xargs | tr " " "," > Sock_Exec.csv

grep -a "Sock_Jitter_Anlyz" /var/log/syslog > ~/Workspace/RTES/HW4/Testing/New/Analysis_Files/Sock_Jitter.txt
awk '{print $7}' "Sock_Jitter.txt" | xargs | tr " " "," > Sock_Jitter.csv

#for f in *; do
#   awk '{print $7}' "$f" | xargs | tr " " ","
#done > result.csv



