#! /bin/bash

echo "Running Config Script"
echo "userspace" > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor

cat /sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq > /sys/devices/system/cpu/cpu5/cpufreq/scaling_min_freq
cat /sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq > /sys/devices/system/cpu/cpu5/cpufreq/scaling_setspeed
echo "cpu5 scaling freq set as below"
cat /sys/devices/system/cpu/cpu5/cpufreq/scaling_max_freq
echo 1 > /sys/devices/system/cpu/cpu5/online

#echo "Setting msgsize_max to 1048576 and msg_max to 1000"
#echo 1048576 | sudo dd of=/proc/sys/fs/mqueue/msgsize_max

#echo 1000 | sudo dd of=/proc/sys/fs/mqueue/msg_max

sysctl kernel.sched_rt_runtime_us=-1
echo "Config Completed"
