#! /bin/bash

grep "JITTER_GREY_R0" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/greyr0.txt

grep "JITTER_GREY_R1" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/greyr1.txt

grep "JITTER_GREY_R2" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/greyr2.txt

grep "JITTER_GREY_R3" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/greyr3.txt

grep "JITTER_GREY_R4" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/greyr4.txt

grep "JITTER_BRIGHT_R0" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/brightr0.txt

grep "JITTER_BRIGHT_R1" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/brightr1.txt

grep "JITTER_BRIGHT_R2" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/brightr2.txt

grep "JITTER_BRIGHT_R3" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/brightr3.txt

grep "JITTER_BRIGHT_R4" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/brightr4.txt

grep "JITTER_CONTRAST_R0" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/contrastr0.txt

grep "JITTER_CONTRAST_R1" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/contrastr1.txt

grep "JITTER_CONTRAST_R2" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/contrastr2.txt

grep "JITTER_CONTRAST_R3" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/contrastr3.txt

grep "JITTER_CONTRAST_R4" /var/log/syslog > ~/Workspace/RTES/HW4/Q5/My_Sol_2/src/analysis_files/contrastr4.txt

for f in *; do
   awk '{print $8}' "$f" | xargs | tr " " ","
done > result.csv



